from .habitat.terrestrial import ITerrestrial
from .animal.freshwater import IFreshwater
from .animal.stagnant import IStagnant
from .habitat.aquatic import IAquatic
from .animal.flying import IFlying
from .animal.walking import IWalking
from .animal.swimming import ISwimming
from .identifiable import Identifiable
from .habitat.contains_animals import IContainsAnimals
from .habitat.contains_plants import IContainsPlants
